FROM bigtruedata/scala:2.12

# install sbt
RUN wget -O- 'https://github.com/sbt/sbt/releases/download/v1.3.3/sbt-1.3.3.tgz' | \
    tar xzf - -C /usr/local --strip-components=1 && sbt exit

WORKDIR /app

# fetch dependencies
COPY project project
COPY *.sbt ./
RUN sbt update

COPY entrypoint.sh /
RUN chmod u+x /entrypoint.sh

# source directories should be mounted under /app

CMD ["sbt", "run"]
ENTRYPOINT ["/entrypoint.sh"]
